package com.em.mapper;

import com.em.vo.Slideshow;
import com.em.vo.SlideshowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SlideshowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    long countByExample(SlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    int deleteByExample(SlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    int insert(Slideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    int insertSelective(Slideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    List<Slideshow> selectByExample(SlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") Slideshow record, @Param("example") SlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    int updateByExample(@Param("record") Slideshow record, @Param("example") SlideshowExample example);
}