package com.em.vo;

import java.io.Serializable;

public class Comment implements Serializable {
    File img;

    public File getImg() {
        return img;
    }

    public void setImg(File img) {
        this.img = img;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.shop_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.is_anonymity
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer isAnonymity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.grade
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Float grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.shop_id
     *
     * @return the value of comment.shop_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.shop_id
     *
     * @param shopId the value for comment.shop_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.is_anonymity
     *
     * @return the value of comment.is_anonymity
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getIsAnonymity() {
        return isAnonymity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.is_anonymity
     *
     * @param isAnonymity the value for comment.is_anonymity
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setIsAnonymity(Integer isAnonymity) {
        this.isAnonymity = isAnonymity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment
     *
     * @return the value of comment.comment
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment
     *
     * @param comment the value for comment.comment
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.grade
     *
     * @return the value of comment.grade
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Float getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.grade
     *
     * @param grade the value for comment.grade
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setGrade(Float grade) {
        this.grade = grade;
    }
}