package com.em.vo;

import java.io.Serializable;
import java.util.List;

public class Merchant implements Serializable {
    //商家头像
    private File file;
    //商家图片介绍
    private List<File> files;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.shop_name
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.phone
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Double phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.shop_type
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer shopType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.address
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.remark
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.send_price
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Float sendPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.lunch_box
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Float lunchBox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    public File getFile() {
        return file;
    }

    public void setFile(File file) {
        this.file = file;
    }

    public List<File> getFiles() {
        return files;
    }

    public void setFiles(List<File> files) {
        this.files = files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.id
     *
     * @return the value of merchant.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.id
     *
     * @param id the value for merchant.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.user_id
     *
     * @return the value of merchant.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.user_id
     *
     * @param userId the value for merchant.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.shop_name
     *
     * @return the value of merchant.shop_name
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.shop_name
     *
     * @param shopName the value for merchant.shop_name
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.phone
     *
     * @return the value of merchant.phone
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Double getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.phone
     *
     * @param phone the value for merchant.phone
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setPhone(Double phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.shop_type
     *
     * @return the value of merchant.shop_type
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.shop_type
     *
     * @param shopType the value for merchant.shop_type
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setShopType(Integer shopType) {
        this.shopType = shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.address
     *
     * @return the value of merchant.address
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.address
     *
     * @param address the value for merchant.address
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.remark
     *
     * @return the value of merchant.remark
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.remark
     *
     * @param remark the value for merchant.remark
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.send_price
     *
     * @return the value of merchant.send_price
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Float getSendPrice() {
        return sendPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.send_price
     *
     * @param sendPrice the value for merchant.send_price
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setSendPrice(Float sendPrice) {
        this.sendPrice = sendPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.lunch_box
     *
     * @return the value of merchant.lunch_box
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Float getLunchBox() {
        return lunchBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.lunch_box
     *
     * @param lunchBox the value for merchant.lunch_box
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setLunchBox(Float lunchBox) {
        this.lunchBox = lunchBox;
    }
}