package com.em.vo;

import java.io.Serializable;
import java.util.Date;

public class Orderfrom implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.shop_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.remark
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.total_price
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Float totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.end_time
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.start_time
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.user_address
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.is_send
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer isSend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.is_comment
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer isComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.is_pay
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer isPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.is_close
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer isClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderfrom
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.id
     *
     * @return the value of orderfrom.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.id
     *
     * @param id the value for orderfrom.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.shop_id
     *
     * @return the value of orderfrom.shop_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.shop_id
     *
     * @param shopId the value for orderfrom.shop_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.user_id
     *
     * @return the value of orderfrom.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.user_id
     *
     * @param userId the value for orderfrom.user_id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.remark
     *
     * @return the value of orderfrom.remark
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.remark
     *
     * @param remark the value for orderfrom.remark
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.total_price
     *
     * @return the value of orderfrom.total_price
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Float getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.total_price
     *
     * @param totalPrice the value for orderfrom.total_price
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.end_time
     *
     * @return the value of orderfrom.end_time
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.end_time
     *
     * @param endTime the value for orderfrom.end_time
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.start_time
     *
     * @return the value of orderfrom.start_time
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.start_time
     *
     * @param startTime the value for orderfrom.start_time
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.user_address
     *
     * @return the value of orderfrom.user_address
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.user_address
     *
     * @param userAddress the value for orderfrom.user_address
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setUserAddress(Integer userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.is_send
     *
     * @return the value of orderfrom.is_send
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.is_send
     *
     * @param isSend the value for orderfrom.is_send
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setIsSend(Integer isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.is_comment
     *
     * @return the value of orderfrom.is_comment
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.is_comment
     *
     * @param isComment the value for orderfrom.is_comment
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setIsComment(Integer isComment) {
        this.isComment = isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.is_pay
     *
     * @return the value of orderfrom.is_pay
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getIsPay() {
        return isPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.is_pay
     *
     * @param isPay the value for orderfrom.is_pay
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setIsPay(Integer isPay) {
        this.isPay = isPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.is_close
     *
     * @return the value of orderfrom.is_close
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getIsClose() {
        return isClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.is_close
     *
     * @param isClose the value for orderfrom.is_close
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setIsClose(Integer isClose) {
        this.isClose = isClose;
    }
}