package com.em.vo;

import java.io.Serializable;

public class Pay implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.add_money
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Float addMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.status
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.id
     *
     * @return the value of pay.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.id
     *
     * @param id the value for pay.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.add_money
     *
     * @return the value of pay.add_money
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Float getAddMoney() {
        return addMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.add_money
     *
     * @param addMoney the value for pay.add_money
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setAddMoney(Float addMoney) {
        this.addMoney = addMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.status
     *
     * @return the value of pay.status
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.status
     *
     * @param status the value for pay.status
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}