package com.em.vo;

import java.io.Serializable;

public class Slideshow implements Serializable {
    private File img;

    public File getImg() {
        return img;
    }

    public void setImg(File img) {
        this.img = img;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.status
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slideshow
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.id
     *
     * @return the value of slideshow.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.id
     *
     * @param id the value for slideshow.id
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.status
     *
     * @return the value of slideshow.status
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.status
     *
     * @param status the value for slideshow.status
     *
     * @mbg.generated Tue Nov 12 16:34:42 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}